DROP DATABASE IF EXISTS test;
CREATE DATABASE test;

DROP TABLE IF EXISTS record;
CREATE TABLE record(
    ID      INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
    VALUE   TEXT
);

INSERT INTO record VALUES(NULL,"Hello");
INSERT INTO record VALUES(NULL,"Hello");

ALTER TABLE record AUTO_INCREMENT=1000;

INSERT INTO record VALUES(NULL,"Goodbye");
SELECT * FROM record;
SELECT DISTINCT(VALUE) FROM record;